### ISSUE TITLE
Is it possible to get a callback when the user closes the ad?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chen-fishbein/admobfullscreen-codenameone#2]
```
If I make a call to showAdIfLoaded() or loadAndShow() there is currently no 
callback to know if the user has returned from the ad (timeout or clicking on 
the 'X')

For example, if I'm trying to show an ad between levels in my app, how could I 
know when to begin the next level? Everything happens asynchronously.

I've found a temporary solution, but all of this would be easily solved if the 
showAdIFLoaded() or loadAndShow() could block until the user returns from 
viewing the ad.
```

Original issue reported on code.google.com by `whoaback...@gmail.com` on 9 Feb 2015 at 11:06

**Comment by chen-fishbein** [comment]
Fixed - added AdsListener

**Comment by dmanyukhin** [comment]
Hi,
is it possible to add callback that fires if user closes ad before time ends (Reward ads) ?
Currently onAdClosed fires in both cases, when user watch ad completely and when user closes ad right after it appears, which is critical for Reward ads, I am surprised that nobody asked about that before
I have though about workaround using timer, but I need to know ads length for that, which is also unavailable, may be you have other idea how to check if user closes ad before time, I will really appreciate any help
Thanks,
Denis

**Comment by codenameone** [comment]
This is the old project, the latest version is here: https://github.com/shannah/admobfullscreen-codenameone/

See this commit https://github.com/shannah/admobfullscreen-codenameone/commit/147ca9c4f83149a8f9d912eea8a8cd8ef7167342

If you need detailed events you can submit a pull request to that project with additional events.
