### ISSUE TITLE
Google will deprecate SDK

### ISSUE THREAD

**Issue by carlosverdier** [chen-fishbein/admobfullscreen-codenameone#5]
Hi

This is just a warning / reminder, maybe you are already aware of this.

I got a email from Google saying this:

Version 6.4.1 and earlier versions of Google ads SDK for mobile (Android) will become obsolete on September 15, 2016. To ensure that your ads continue after September 15, 2016, update your Google Ads SDK Mobile to version 7.0.0 or later.

Is this cn1lib ready for this? 

Shai suggested cocoapods to make the project safe for future releases, although I understand that this solutions will be for iOS only.

https://www.codenameone.com/blog/cocoapods.html

Thanks

**Comment by shannah** [comment]
Please try changing the `android.includeGPlayServices=true` build hint to `android.playService.ads=true`

That should update it to use a newer version (8.3.0 right now, and will be updated soon to a later version).

**Comment by carlosverdier** [comment]
It works! Thank you, just on time because Google extended the deadline to October 17.
